version: "3.8"

secrets:
  postgres_password:
    external: true

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "orchestrator"
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres_password"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - labstack_net
    secrets:
      - source: postgres_password
        target: postgres_password
    deploy:
      replicas: 1

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - labstack_net
    deploy:
      replicas: 1

  orchestrator:
    image: orchestrator-local:latest
    environment:
      DB_USER: "postgres"
      DB_NAME: "orchestrator"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_PASSWORD_FILE: "/run/secrets/postgres_password"
    depends_on:
      - postgres
      - redis
    secrets:
      - source: postgres_password
        target: postgres_password
    networks:
      - labstack_net
    deploy:
      replicas: 1

networks:
  labstack_net:
    driver: overlay
    attachable: true

volumes:
  pgdata: {}
  redis_data: {}
