name: "Bug report"
description: "Reportar un defecto reproducible"
title: "fix: <resumen del bug>"
labels: ["type:bug","prio:P1","status:ready"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Descripción
      placeholder: "Qué ocurre vs qué debería ocurrir"
    validations:
      required: true
  - type: textarea
    id: repro_steps
    attributes:
      label: Pasos para reproducir
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: Resultado esperado
    validations:
      required: true
  - type: input
    id: actual
    attributes:
      label: Resultado actual
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/Stacktrace
      render: shell
  - type: input
    id: env
    attributes:
      label: Entorno (OS/versión/commit/servicio)
      placeholder: "Windows 11 / commit abc123 / api-gateway:1.0"
  - type: dropdown
    id: severity
    attributes:
      label: Severidad
      options:
        - S0 Bloqueante
        - S1 Alta
        - S2 Media
        - S3 Baja
    validations:
      required: true
  - type: checkboxes
    id: safeguards
    attributes:
      label: Salvaguardas
      options:
        - label: "Reproducible en main"
        - label: "Test de regresión agregado"
        - label: "Fix pequeño y con rollback fácil"
  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done
      options:
        - label: "Test de regresión pasa"
        - label: "Lint/format OK"
        - label: "Root cause documentada"
        - label: "Aprobado en Code Review"
