blank_issues_enabled: false
contact_links:
  - name: Preguntas o soporte
    url: https://github.com/MaximilianoTobio/agentes-ai-equipo-desarrollo/discussions
    about: Usa Discussions para consultas generales.
